apiVersion: v1
kind: Secret
metadata:
  name: git-base-auth
  annotations:
    tekton.dev/git-1: https://192.168.0.110
type: kubernetes.io/basic-auth
stringData:
  username: xxxx
  password: xxxxxxxxxxxxx
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
data:
  config.json: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5aGIwQjVaV0ZvTG01bGREcHpkMnd4T1RnM01USXlNUT09IgoJCX0KCX0KfQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-credentials
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: "abc123456"
---
# 创建serviceaccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-credentials
secrets:
- name: ssh-key-for-git
- name: git-base-auth
- name: aliyun-registry