apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-build
spec:
  workspaces:
    - name: source-dir
  steps:
    - name: run-test-go
      image: golang:1.19-alpine
      workingDir: $(workspaces.source-dir.path)
      env:
        - name: GOPROXY
          value: "https://goproxy.cn,direct"
        - name: GOOS
          value: "linux"
        - name: CGO_ENABLED
          value: "0"
      script: |
        go mod download
        go build -ldflags="-s -w" -o ./app ./main.go